# 1. Site settings
theme: jekyll-theme-minimal
logo: "/assets/logos/logo.jpg"
title: "Eugenie Y. Lai"
author: "Eugenie Y. Lai"
email: "eugenie.y.lai@gmail.com"
google_analytics: "UA-167616887-1"

# 2. Collection
collections:
  posts:
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/eugenie-lai
  GitHub: https://github.com/eugenielai