# 1. Site settings
#theme: jekyll-theme-minimal
logo: "/assets/logos/logo.jpg"
title: "Eugenie Lai"
author: Eugenie Lai
email: "eugenie.y.lai@gmail.com"

# 2. Collection
collections:
  posts:
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/eugenie-yujing-lai
  GitHub: https://github.com/eugenielai