# 1. Site settings
theme: jekyll-theme-minimal
logo: "/assets/logos/logo.jpg"
title: "Eugenie Lai"
email: "eugenie.y.lai@gmail.com"

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page

# 4. Collection
collections:
  posts:
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/eugenie-yujing-lai
  GitHub: https://github.com/eugenielai